[general]
host = "0.0.0.0"
port = 80
root = "./"

log-level = "error"
log-remote-address = false

directory-listing = false
cache-control-headers = false

cors-allow-origins = "*"
index-files = "index.html"

ignore-hidden-files = true
disable-symlinks = true

# MIMEタイプの追加（GLB/GLTF対応）
mime-types = [
  { extension = "glb",  type = "model/gltf-binary" },
  { extension = "gltf", type = "model/gltf+json" }
]

[advanced]

[[advanced.headers]]
source = "**"
[advanced.headers.headers]
Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
Pragma = "no-cache"
Expires = "0"
